apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: users_ms=anzeha/ffantasy.users,squads_ms=anzeha/ffantasy.squads,web_ms=anzeha/ffantasy.web,gw_processor_ms=anzeha/ffantasy.gameweek-processor,domain_ms=anzeha/ffantasy.domain
    
    argocd-image-updater.argoproj.io/users_ms.update-strategy: latest
    argocd-image-updater.argoproj.io/users_ms.allow-tags: regexp:^staging.*

    argocd-image-updater.argoproj.io/squads_ms.update-strategy: latest
    argocd-image-updater.argoproj.io/squads_ms.allow-tags: regexp:^staging.*

    argocd-image-updater.argoproj.io/web_ms.update-strategy: latest
    argocd-image-updater.argoproj.io/web_ms.allow-tags: regexp:^staging.*

    argocd-image-updater.argoproj.io/gw_processor_ms.update-strategy: latest
    argocd-image-updater.argoproj.io/gw_processor_ms.allow-tags: regexp:^staging.*

    argocd-image-updater.argoproj.io/domain_ms.update-strategy: latest
    
    argocd-image-updater.argoproj.io/git-branch: staging

    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/repo-deploy-key
    argocd-image-updater.argoproj.io/users_ms.force-update: "true"
    argocd-image-updater.argoproj.io/game_domain_ms.force-update: "true"
    argocd-image-updater.argoproj.io/game_logic_ms.force-update: "true"
  namespace: argocd
  name: floorball-fantasy-dev
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:  
  project: default
  source:   
    repoURL: 'https://github.com/anzeha/floorball-fantasy-chart.git'  
    targetRevision: staging  
    path: .
    helm:
      releaseName: ffantasy
      valueFiles:
        - ./environments/values-staging.yml
  destination:  
    server: 'https://34.91.225.127'  
    namespace: floorball-fantasy
  syncPolicy:  
    automated:  
      prune: true