apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-application-controller
  namespace: argocd
  annotations:
    iam.gke.io/gcp-service-account: "argocd-sa@deployment-433913.iam.gserviceaccount.com"
