apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: floorball-fantasy
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/anzeha/floorball-fantasy-deployment.git
    path: k8s
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: floorball-fantasy
  syncPolicy:
    automated:
      selfHeal: true