apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cicd-gke-cluster-dev
  namespace: argocd
spec:
  secretStoreRef:
    name: gcp-secrets
    kind: ClusterSecretStore
  target:
    name: cicd-gke-cluster-dev
    creationPolicy: 'Owner'
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
          environment: dev
      data:
        name: "{{ .clusterName }}"
        server: "{{ .host }}"
        config: |
          {
            "execProviderConfig": {
              "command": "argocd-k8s-auth",
              "args": ["gcp"],
              "apiVersion": "client.authentication.k8s.io/v1beta1"
            },
            "tlsClientConfig": {
              "insecure": false,
              "caData": "{{ .caData }}"
            }
          }
  data:
    - secretKey: clusterName
      remoteRef:
        key: cicd-gke-cluster-dev
        property: clusterName
    
    - secretKey: host
      remoteRef:
        key: cicd-gke-cluster-dev
        property: host
    
    - secretKey: caData
      remoteRef:
        key: cicd-gke-cluster-dev
        property: caData
        decodingStrategy: None